export const NEW = [];
export const UPDATED = [];

export const CATEGORIES = [
  {
    name: 'Get Started',
    subcategories: ['Introduction']
  },
  {
    name: 'Components',
    subcategories: ['Fill Button',
      'Sidebar',
      'Dropdown',
      'Pill Nav',
      'Like Button',
      'Segmented Toggle',
      'Animated Menu',
      'Rainbow Button',
      'Otp Input',
      'Tooltip',
      'Score Meter',
      'Rubber Slider',
      'Star Rating',
      'Theme Toggle',
      'Tilt Card',
      'Avatar Stack',
      'Copy Button',
      'Magnetic Button',
      'Accordion',
      'Toast',
      'Dock',
      'Floating Input',
      'Hold Button',
      'Mood Picker',
      'Peek Password',
      'Swipe Action',
      'Spotlight Card',
      'Border Beam',
      'Confetti Button',
      'Marquee',
      'Radial Progress',
      'Range Slider',
      'Command Palette',
      'Reorder List',
      'Stepper',
      'Flip Card',
      'Tag Input',
      'Tabs',
      'Speed Dial',
      'Reaction Bar',
      'Split Pane',
      'Stage Tracker',
      'Gooey Menu',
      'Password Strength',
      'Ripple Button',
      'Bottom Sheet',
      'Color Picker',
      'Notification Stack',
      'File Drop',
      'Image Compare'
    ]
  },
  {
    name: '3D',
    subcategories: ['Poster Drum',
      'Poster Helix',
      'Cover Flow',
      'Card Deck',
      'Cube Showcase',
      'Tag Sphere',
      'Depth Tunnel'
    ]
  },
  {
    name: 'Scroll',
    subcategories: ['Honeycomb Grid',
      'Scroll Stack',
      'Scroll Velocity',
      'Scroll Reveal',
      'Horizontal Scroll',
      'Scroll Progress',
      'Parallax Scroll',
      'Scroll Spy Nav',
      'Sticky Grid Scroll',
      'Path Draw',
      'Scroll Timeline',
      'Scroll Mask',
      'Scroll Float',
      'Scroll Zoom',
      'Reading Highlight',
      'Scroll Rotate',
      'Scroll Snap',
      'Scale Carousel',
      'Arc Carousel',
      'Focus Carousel',
      'Tilt Carousel'
    ]
  },
  {
    name: 'Text Animations',
    subcategories: ['Scramble Text', 'Number Ticker', 'Typewriter Text', 'Shiny Text', 'Split Text', 'Blur Text']
  },
  {
    name: 'Backgrounds',
    subcategories: [
      'Dot Grid',
      'Aurora',
      'Particles',
      'Ripple',
      'Waves',
      'Grid',
      'Beams',
      'Threads',
      'Starfield',
      'Plasma',
      'Grain',
      'Flow Field',
      'Mesh Gradient',
      'Lightning',
      'Liquid Metal',
      'Constellation',
      'Hex Pulse',
      'Noise Contours',
      'Rain',
      'Vortex',
      'Liquid Chrome',
      'Liquid Glass',
      'Iridescence'
    ]
  }
];
